"""Biologist-readable figures for GR-Neutro × concept adapter.

Replaces make_figures.py for presentation. Key fixes:
- Attention maps OVERLAID on the cell image (jet, alpha=0.45) instead of separate heatmap squares.
- Classified vs misclassified galleries with predicted-concept bars next to each cell.
- Per-class and per-concept breakdown bar charts with the 0.90 target line.
- Clean CSV/TeX tables.

Reads outputs/<tag>/predictions.pt + eval.json. Uses model.pt only when present
(for prior C); ensembles fall back to concept_config_gr_neutro.json.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from PIL import Image
from sklearn.metrics import f1_score


HERE = Path(__file__).resolve().parent
WORKDIR = Path("/gpfs/workdir/mouaddenn")


def load_run(tag: str, root: Path):
    rd = root / tag
    out = dict(tag=tag, run_dir=rd)
    out["pred"] = torch.load(rd / "predictions.pt", map_location="cpu", weights_only=False)
    out["summary"] = json.loads((rd / "summary.json").read_text())
    if (rd / "eval.json").exists():
        out["eval"] = json.loads((rd / "eval.json").read_text())
    else:
        out["eval"] = {}
    log_path = rd / "training_log.csv"
    if log_path.exists():
        out["log"] = list(csv.reader(open(log_path)))
    else:
        out["log"] = None
    return out


# ----------------------------- Tables ----------------------------------------
def fig_main_table(runs: dict, out_dir: Path):
    """One row per run; columns = the four target metrics + per-class + per-concept rollups.

    Tuned values from eval.json preferred over summary.json raw.
    """
    rows = []
    classes = next(iter(runs.values()))["pred"]["class_names"]
    concepts = next(iter(runs.values()))["pred"]["concepts"]
    for tag, r in runs.items():
        e = r["eval"]
        s = r["summary"]
        ct = e.get("classification_tuned", {})
        co = e.get("concept_tuned", {})
        co_pc = co.get("per_concept_f1", [])
        ct_pc = ct.get("per_class_f1", [])
        row = dict(run=tag,
                    weighted_f1=ct.get("weighted_f1", float("nan")),
                    macro_f1=ct.get("macro_f1", float("nan")),
                    mean_concept_f1=co.get("mean_concept_f1", float("nan")),
                    coverage_at_0p05=e.get("conformal", {}).get("marginal_positive_coverage", float("nan")),
                    probe_weighted_f1=e.get("completeness_probe", {}).get("weighted_f1", float("nan")),
                    probe_subset_acc=e.get("completeness_probe", {}).get("subset_accuracy", float("nan")),
                    min_class_f1=float(np.min(ct_pc)) if ct_pc else float("nan"),
                    min_concept_f1=float(np.min(co_pc)) if co_pc else float("nan"),
                    n_classes_above_0p90=int(sum(1 for f in ct_pc if f >= 0.90)),
                    n_concepts_above_0p90=int(sum(1 for f in co_pc if f >= 0.90)),
                    )
        rows.append(row)
    csv_path = out_dir / "main_results_table.csv"
    fields = list(rows[0].keys())
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        rows.sort(key=lambda r: r.get("weighted_f1") or -1, reverse=True)
        w.writerows(rows)
    # Per-class breakdown CSV — one row per (run, class) for easy filtering
    pc_path = out_dir / "per_class_breakdown.csv"
    with open(pc_path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["run", "class", "F1_tuned", "F1_at_0p90"])
        for tag, r in runs.items():
            f1s = r["eval"].get("classification_tuned", {}).get("per_class_f1", [])
            for c, f1 in zip(classes, f1s):
                w.writerow([tag, c, f"{f1:.4f}", "yes" if f1 >= 0.90 else "no"])
    pc_concept_path = out_dir / "per_concept_breakdown.csv"
    with open(pc_concept_path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["run", "concept", "F1_tuned", "F1_at_0p90"])
        for tag, r in runs.items():
            f1s = r["eval"].get("concept_tuned", {}).get("per_concept_f1", [])
            for c, f1 in zip(concepts, f1s):
                w.writerow([tag, c, f"{f1:.4f}", "yes" if f1 >= 0.90 else "no"])
    print(f"[per_class_csv] {pc_path}\n[per_concept_csv] {pc_concept_path}")
    # LaTeX with target line
    tex = ["% Main results — ≥0.90 means hit target. Generated by make_figures_v2.py."]
    tex.append("\\begin{tabular}{lcccccc}\\toprule")
    tex.append("Run & W-F1 & Concept F1 & Cov\\,$\\alpha=.05$ & Probe W-F1 & "
                "min cls F1 & min con F1 \\\\\\midrule")
    for r in rows:
        def f(v):
            return "-" if v is None or (isinstance(v, float) and np.isnan(v)) else f"{v:.3f}"
        tag_safe = r["run"].replace("_", "\\_")
        tex.append("\\texttt{" + tag_safe + "} & "
                    f"{f(r['weighted_f1'])} & {f(r['mean_concept_f1'])} & "
                    f"{f(r['coverage_at_0p05'])} & {f(r['probe_weighted_f1'])} & "
                    f"{f(r['min_class_f1'])} & {f(r['min_concept_f1'])} \\\\")
    tex.append("\\bottomrule\\end{tabular}")
    (out_dir / "main_results_table.tex").write_text("\n".join(tex))

    # Render the same table as a PDF using matplotlib (no LaTeX dependency).
    cell_text = []
    headers = ["Run", "W-F1", "Concept F1", "Cov α=.05", "Probe W-F1",
                "min cls F1", "min con F1", "n cls ≥0.9", "n con ≥0.9"]
    def f(v):
        return "—" if v is None or (isinstance(v, float) and np.isnan(v)) else f"{v:.3f}"
    for row in rows:
        cell_text.append([
            row["run"], f(row["weighted_f1"]), f(row["mean_concept_f1"]),
            f(row["coverage_at_0p05"]), f(row["probe_weighted_f1"]),
            f(row["min_class_f1"]), f(row["min_concept_f1"]),
            str(row["n_classes_above_0p90"]), str(row["n_concepts_above_0p90"]),
        ])
    fig, ax = plt.subplots(figsize=(13, max(2.5, 0.5 * (len(rows) + 1))))
    ax.axis("off")
    table = ax.table(cellText=cell_text, colLabels=headers, loc="center",
                      cellLoc="center", colLoc="center")
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1.0, 1.4)
    # Color the header row + best row
    for j in range(len(headers)):
        table[(0, j)].set_facecolor("#cccccc")
        table[(0, j)].set_text_props(weight="bold")
    # Highlight best row (highest weighted_f1)
    best_row = max(range(len(rows)), key=lambda i: rows[i].get("weighted_f1") or -1)
    for j in range(len(headers)):
        table[(best_row + 1, j)].set_facecolor("#dff0d8")
    fig.suptitle("GR-Neutro × concept adapter — main results", fontsize=11)
    fig.tight_layout()
    fig.savefig(out_dir / "main_results_table.pdf", bbox_inches="tight")
    fig.savefig(out_dir / "main_results_table.png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"[main_table] {csv_path}, .pdf, .png")
    return rows


def fig_per_class_breakdown(runs: dict, out_dir: Path):
    """Per-class F1 bar chart with target line. Annotates which classes hit ≥0.90."""
    classes = next(iter(runs.values()))["pred"]["class_names"]
    fig, ax = plt.subplots(figsize=(9, max(3.5, 0.7 * len(runs))))
    n_runs = len(runs)
    width = 0.8 / n_runs
    x = np.arange(len(classes))
    palette = plt.get_cmap("tab10")
    for i, (tag, r) in enumerate(runs.items()):
        f1s = r["eval"].get("classification_tuned", {}).get("per_class_f1", [])
        if not f1s:
            continue
        bars = ax.bar(x + i * width, f1s, width=width, label=tag, color=palette(i))
        for bx, val in zip(bars, f1s):
            if val >= 0.90:
                ax.text(bx.get_x() + bx.get_width()/2, val + 0.005, "✓",
                        ha="center", fontsize=9, color="green")
    ax.axhline(0.90, color="r", ls="--", lw=1, label="target 0.90")
    ax.set_xticks(x + width * (n_runs - 1) / 2)
    ax.set_xticklabels(classes, rotation=20, ha="right")
    ax.set_ylabel("Per-class F1 (test, tuned thresholds)")
    ax.set_ylim(0, 1.05)
    ax.legend(loc="lower right", fontsize=8)
    ax.set_title("Classification F1 per class — target ≥ 0.90")
    fig.tight_layout()
    fig.savefig(out_dir / "per_class_f1.pdf")
    fig.savefig(out_dir / "per_class_f1.png", dpi=150)
    plt.close(fig)
    print(f"[per_class] {out_dir}/per_class_f1.pdf")


def fig_per_concept_breakdown(runs: dict, out_dir: Path):
    """Per-concept F1 bar chart with target line."""
    concepts = next(iter(runs.values()))["pred"]["concepts"]
    fig, ax = plt.subplots(figsize=(11, max(3.5, 0.7 * len(runs))))
    n_runs = len(runs)
    width = 0.8 / n_runs
    x = np.arange(len(concepts))
    palette = plt.get_cmap("tab10")
    for i, (tag, r) in enumerate(runs.items()):
        f1s = r["eval"].get("concept_tuned", {}).get("per_concept_f1", [])
        if not f1s:
            continue
        bars = ax.bar(x + i * width, f1s, width=width, label=tag, color=palette(i))
        for bx, val in zip(bars, f1s):
            if val >= 0.90:
                ax.text(bx.get_x() + bx.get_width()/2, val + 0.005, "✓",
                        ha="center", fontsize=9, color="green")
    ax.axhline(0.90, color="r", ls="--", lw=1, label="target 0.90")
    ax.set_xticks(x + width * (n_runs - 1) / 2)
    ax.set_xticklabels([c.replace("_", " ") for c in concepts],
                        rotation=30, ha="right", fontsize=8)
    ax.set_ylabel("Per-concept F1 (test, tuned thresholds)")
    ax.set_ylim(0, 1.05)
    ax.legend(loc="lower right", fontsize=8)
    ax.set_title("Concept F1 per concept — target ≥ 0.90")
    fig.tight_layout()
    fig.savefig(out_dir / "per_concept_f1.pdf")
    fig.savefig(out_dir / "per_concept_f1.png", dpi=150)
    plt.close(fig)
    print(f"[per_concept] {out_dir}/per_concept_f1.pdf")


# ----------------------------- Attention overlay ----------------------------
def attn_to_overlay(attn_kp: np.ndarray, grid_hw: tuple[int, int], out_size: int = 224):
    """One sample's K-th attention vector → upsampled, normalized heatmap on cell."""
    h, w = grid_hw
    a = attn_kp.reshape(h, w)
    a = (a - a.min()) / (a.max() - a.min() + 1e-9)
    return np.array(Image.fromarray((a * 255).astype(np.uint8))
                    .resize((out_size, out_size), Image.BILINEAR))


def fig_attention_overlay(primary: dict, out_dir: Path, data_root: Path,
                            filename_lookup: dict):
    """One row per class. Cell image | top-3 most relevant concepts (by class definition)
    overlaid on the same image. Picks cells where attention is concentrated on the
    central cell region (not on background RBCs/empty space).
    """
    pred = primary["pred"]
    if "attn" not in pred["test"]:
        print("[attn_overlay] no attn maps; skipping")
        return
    attn = pred["test"]["attn"].numpy()             # (N, K, P)
    cls_p = pred["test"]["class_logits"].sigmoid().numpy()
    con_p = pred["test"]["concept_logits"].sigmoid().numpy()
    y = pred["test"]["labels"].numpy().astype(int)
    e = primary.get("eval", {})
    thr = np.array(e.get("classification_tuned", {}).get("thresholds",
                                                            [0.5] * len(pred["class_names"])))
    pred_h = (cls_p >= thr[None, :]).astype(int)
    no_pred = pred_h.sum(axis=1) == 0
    if no_pred.any():
        ratio = cls_p / thr[None, :]
        for i in np.where(no_pred)[0]:
            pred_h[i, int(np.argmax(ratio[i]))] = 1
    classes = pred["class_names"]
    concepts = pred["concepts"]
    P = attn.shape[2]
    side = int(round(P ** 0.5))
    grid_hw = (side, side)

    # Build a "centrality" score for each (cell, concept). Cell images are
    # centered, so the cell occupies roughly the central 50% of the patch grid.
    # High score = attention concentrates on cell, not background.
    h, w = grid_hw
    cy_lo, cy_hi = int(h * 0.20), int(h * 0.80)
    cx_lo, cx_hi = int(w * 0.20), int(w * 0.80)
    center_mask = np.zeros((h, w), dtype=bool)
    center_mask[cy_lo:cy_hi, cx_lo:cx_hi] = True
    center_mask_flat = center_mask.flatten()
    # centrality_kc[i, c] = fraction of total attention inside the central window
    a_norm = attn / (attn.sum(axis=2, keepdims=True) + 1e-9)
    centrality = a_norm[:, :, center_mask_flat].sum(axis=2)   # (N, K)

    # Identify which concepts are "defining" for each class (docx |dev from baseline| ≥ 0.1).
    cfg_path = HERE / "concept_config_gr_neutro.json"
    cfg = json.loads(cfg_path.read_text())
    class_concept = np.array(cfg["class_to_concept_matrix"]["matrix"])
    baseline = class_concept[cfg.get("normal_class_index", 0)]
    rel_per_class = np.abs(class_concept - baseline)   # (n_classes, n_concepts)
    # If Normal class — all values are baseline; pick the highest-magnitude concepts among those
    # actually present (lobulation, granule_density, etc. that have value > 0.4).
    rel_per_class[0] = np.abs(class_concept[0] - 0.0)

    # Pick one CORRECTLY classified cell per class, scoring by attention centrality
    # only (not by "defining concept"). For each candidate cell we'll later show
    # the model's OWN top-3 predicted concepts (whichever they are, p>=0.9), so
    # attention maps are guaranteed to fire on something the model thinks is present.
    picked = []
    for k, cls in enumerate(classes):
        mask = (y[:, k] == 1) & np.all(pred_h == y, axis=1)
        idxs = np.where(mask)[0]
        if len(idxs) == 0:
            mask = (y[:, k] == 1) & (pred_h[:, k] == 1)
            idxs = np.where(mask)[0]
        if len(idxs) == 0:
            continue
        # Score by: (a) need >=2 concepts predicted with prob>=0.9 (so we have
        # something focused to show), (b) centrality of top concepts.
        n_high_prob = (con_p[idxs] >= 0.9).sum(axis=1)
        # Mean centrality across the top-K predicted concepts (K=3 if >=3 high-prob, else all)
        mean_centrality = []
        for ci_local, ci in enumerate(idxs):
            top_pred_concepts = np.argsort(-con_p[ci])[:3]
            mean_centrality.append(centrality[ci, top_pred_concepts].mean())
        mean_centrality = np.array(mean_centrality)
        # Score: prefer >=2 high-prob concepts; among them, max centrality.
        score = mean_centrality + 0.5 * (n_high_prob >= 2).astype(float) + 0.3 * cls_p[idxs, k]
        best = idxs[int(np.argmax(score))]
        picked.append((cls, int(best)))

    n_top_concepts = 3
    fig, axes = plt.subplots(len(picked), 1 + n_top_concepts,
                              figsize=((1 + n_top_concepts) * 2.2, 2.4 * len(picked)))
    if len(picked) == 1:
        axes = axes[None, :]
    for r, (cls_name, ci) in enumerate(picked):
        fname = filename_lookup.get(int(pred["test_idx"][ci]), None)
        cand = list(data_root.rglob(fname)) if fname else []
        img = Image.open(cand[0]).convert("RGB").resize((224, 224)) if cand else Image.new("RGB", (224,224), (128,128,128))
        ax0 = axes[r, 0]
        ax0.imshow(img)
        ax0.set_xticks([]); ax0.set_yticks([])
        ax0.set_ylabel(cls_name, fontsize=10, rotation=0, ha="right", va="center")
        if r == 0:
            ax0.set_title("cell image", fontsize=10)
        # Show the cell's OWN top-3 predicted concepts (not textbook "defining" —
        # this guarantees attention fires on something the model thinks is present).
        top3 = np.argsort(-con_p[ci])[:n_top_concepts]
        for j, kc in enumerate(top3):
            heat = attn_to_overlay(attn[ci, kc], grid_hw)
            ax = axes[r, j + 1]
            ax.imshow(img)
            ax.imshow(heat, cmap="jet", alpha=0.45)
            ax.set_xticks([]); ax.set_yticks([])
            label = concepts[kc].replace("_", "\n")
            cell_centrality = centrality[ci, kc]
            ax.set_title(f"{label}\np={con_p[ci, kc]:.2f}  (centr.={cell_centrality:.2f})", fontsize=7)
    fig.suptitle("Where the model looks per defining concept (cells filtered for centrality)", fontsize=12)
    fig.tight_layout()
    fig.savefig(out_dir / "attention_overlay.pdf")
    fig.savefig(out_dir / "attention_overlay.png", dpi=150)
    plt.close(fig)
    print(f"[attn_overlay] {out_dir}/attention_overlay.pdf  rows={len(picked)}")


# ---------------------- Classified / Misclassified galleries -----------------
def _load_image(test_idx, ci, filename_lookup, data_root):
    fname = filename_lookup.get(int(test_idx[ci]), None)
    if not fname:
        return None
    cand = list(data_root.rglob(fname))
    if not cand:
        return None
    return Image.open(cand[0]).convert("RGB")


def fig_classified_examples(primary: dict, out_dir: Path, data_root: Path,
                              filename_lookup: dict, k_per_class: int = 2):
    """For each class, show k correctly-classified examples + a horizontal bar of
    predicted concept probabilities. Uses tuned thresholds + argmax fallback.
    """
    pred = primary["pred"]
    cls_p = pred["test"]["class_logits"].sigmoid().numpy()
    con_p = pred["test"]["concept_logits"].sigmoid().numpy()
    y = pred["test"]["labels"].numpy().astype(int)
    classes = pred["class_names"]
    concepts = pred["concepts"]
    test_idx = pred["test_idx"]
    e = primary.get("eval", {})
    thr = np.array(e.get("classification_tuned", {}).get("thresholds",
                                                            [0.5] * len(classes)))
    pred_h = (cls_p >= thr[None, :]).astype(int)
    no_pred = pred_h.sum(axis=1) == 0
    if no_pred.any():
        ratio = cls_p / thr[None, :]
        for i in np.where(no_pred)[0]:
            pred_h[i, int(np.argmax(ratio[i]))] = 1

    # Pick examples
    examples = []
    for k, cls in enumerate(classes):
        # correct: predictions match labels exactly AND this class is positive
        mask = (y[:, k] == 1) & np.all(pred_h == y, axis=1)
        idxs = np.where(mask)[0]
        if len(idxs) >= k_per_class:
            picks = idxs[:k_per_class]
        else:
            picks = idxs[:k_per_class] if len(idxs) > 0 else []
        for ci in picks:
            examples.append((cls, int(ci)))

    if not examples:
        return
    rows = len(examples)
    fig, axes = plt.subplots(rows, 2, figsize=(11, 2.0 * rows),
                              gridspec_kw={"width_ratios": [1.1, 2.5]})
    if rows == 1:
        axes = axes[None, :]
    for r, (cls_name, ci) in enumerate(examples):
        img = _load_image(test_idx, ci, filename_lookup, data_root)
        if img is not None:
            axes[r, 0].imshow(img)
        axes[r, 0].set_xticks([]); axes[r, 0].set_yticks([])
        # Show ALL active labels via xlabel below image
        truth_classes = ", ".join(classes[k] for k in np.where(y[ci]==1)[0])
        axes[r, 0].set_xlabel(truth_classes, fontsize=9, labelpad=4)
        if r == 0:
            axes[r, 0].set_title("Cell (true label)", fontsize=10)
        # Concept bar chart
        ax = axes[r, 1]
        order = np.argsort(con_p[ci])[::-1]
        bars = ax.barh(range(len(concepts)), con_p[ci][order], color="steelblue")
        for bx, v in zip(bars, con_p[ci][order]):
            ax.text(min(v + 0.01, 0.97), bx.get_y() + bx.get_height()/2, f"{v:.2f}",
                    va="center", fontsize=7)
        ax.axvline(0.5, color="k", lw=0.5, ls="--")
        ax.set_yticks(range(len(concepts)))
        ax.set_yticklabels([concepts[i].replace("_", " ") for i in order], fontsize=8)
        ax.invert_yaxis()
        ax.set_xlim(0, 1.05)
        if r == 0:
            ax.set_title("Predicted concept probabilities", fontsize=10)
    fig.suptitle("Correctly classified cells with predicted concepts", fontsize=12)
    fig.tight_layout()
    fig.savefig(out_dir / "correct_examples.pdf")
    fig.savefig(out_dir / "correct_examples.png", dpi=150)
    plt.close(fig)
    print(f"[correct] {out_dir}/correct_examples.pdf  n={rows}")


def fig_misclassified_examples(primary: dict, out_dir: Path, data_root: Path,
                                  filename_lookup: dict, n: int = 12):
    """Misclassified test cells with TRUE vs PREDICTED label and concept probs.
    Biologist can read WHY (which concepts predicted differ from typical class profile).

    Uses tuned per-class thresholds when available so what's shown matches the
    headline F1 numbers. If no class crosses its threshold for a cell, we fall back
    to the argmax class — every cell IS some class biologically.
    """
    pred = primary["pred"]
    cls_p = pred["test"]["class_logits"].sigmoid().numpy()
    con_p = pred["test"]["concept_logits"].sigmoid().numpy()
    y = pred["test"]["labels"].numpy().astype(int)
    classes = pred["class_names"]
    concepts = pred["concepts"]
    test_idx = pred["test_idx"]

    # Apply tuned thresholds (if available) so the predictions match the headline F1.
    e = primary.get("eval", {})
    thr = np.array(e.get("classification_tuned", {}).get("thresholds",
                                                            [0.5] * len(classes)))
    pred_h = (cls_p >= thr[None, :]).astype(int)
    # Fallback: if no class crosses its threshold, assign argmax(prob/threshold).
    no_pred = pred_h.sum(axis=1) == 0
    if no_pred.any():
        ratio = cls_p / thr[None, :]
        for i in np.where(no_pred)[0]:
            pred_h[i, int(np.argmax(ratio[i]))] = 1

    wrong = np.where(np.any(pred_h != y, axis=1))[0]
    if len(wrong) == 0:
        return
    # Try to balance across rare classes — pick at least 1 from each rare class
    # where the cell was misclassified. Fill remainder with random.
    rng = np.random.default_rng(0)
    rare_classes = [k for k, cls in enumerate(classes) if (y[:, k] == 1).sum() < 50]
    chosen = []
    for k in rare_classes:
        cands = [w for w in wrong if y[w, k] == 1]
        if cands:
            chosen.append(int(rng.choice(cands)))
    remain = [w for w in wrong if w not in chosen]
    if len(chosen) < n and remain:
        extras = rng.choice(remain, size=min(n - len(chosen), len(remain)), replace=False)
        chosen.extend([int(x) for x in extras])
    chosen = chosen[:n]
    if not chosen:
        return
    rows = len(chosen)
    # Wider figure, left margin for labels.
    fig, axes = plt.subplots(rows, 2, figsize=(11, 2.2 * rows),
                              gridspec_kw={"width_ratios": [1.1, 2.5]})
    if rows == 1:
        axes = axes[None, :]
    for r, ci in enumerate(chosen):
        img = _load_image(test_idx, ci, filename_lookup, data_root)
        if img is not None:
            axes[r, 0].imshow(img)
        axes[r, 0].set_xticks([]); axes[r, 0].set_yticks([])
        truth = ", ".join(classes[k] for k in np.where(y[ci] == 1)[0]) or "(none)"
        predicted = ", ".join(classes[k] for k in np.where(pred_h[ci] == 1)[0]) or "(none)"
        # Use xlabel below image for the label, keeping vertical layout clean
        axes[r, 0].set_xlabel(f"TRUE: {truth}\nPRED: {predicted}",
                                 fontsize=8, labelpad=4)
        if r == 0:
            axes[r, 0].set_title("Cell", fontsize=10)
        # Concept bar
        ax = axes[r, 1]
        order = np.argsort(con_p[ci])[::-1]
        # Highlight bars where predicted differs from class-typical (deviation from
        # docx baseline) — color cue for biologist
        concept_vals = con_p[ci][order]
        bars = ax.barh(range(len(concepts)), concept_vals, color="steelblue")
        # Red horizontal at p>=0.5 + concept that disagrees with majority truth class
        if np.any(y[ci] == 1):
            true_class_idx = int(np.argmax(y[ci]))
            cfg_path = HERE / "concept_config_gr_neutro.json"
            cfg = json.loads(cfg_path.read_text())
            class_concept_arr = np.array(cfg["class_to_concept_matrix"]["matrix"])
            true_profile_hard = (class_concept_arr[true_class_idx] >= 0.5).astype(int)
            for j, idx_orig in enumerate(order):
                pred_pos = concept_vals[j] >= 0.5
                expected_pos = true_profile_hard[idx_orig] == 1
                if pred_pos != expected_pos:
                    bars[j].set_color("#d62728")
        for bx, v in zip(bars, concept_vals):
            ax.text(min(v + 0.01, 0.97), bx.get_y() + bx.get_height()/2, f"{v:.2f}",
                    va="center", fontsize=7)
        ax.axvline(0.5, color="k", lw=0.5, ls="--")
        ax.set_yticks(range(len(concepts)))
        ax.set_yticklabels([concepts[i].replace("_", " ") for i in order], fontsize=8)
        ax.invert_yaxis()
        ax.set_xlim(0, 1.05)
        if r == 0:
            ax.set_title("Predicted concept probabilities (red = mismatch with TRUE class profile)", fontsize=9)
    fig.suptitle("Misclassified test cells — what the model 'saw'", fontsize=12)
    fig.tight_layout()
    fig.savefig(out_dir / "misclassified_examples.pdf")
    fig.savefig(out_dir / "misclassified_examples.png", dpi=150)
    plt.close(fig)
    print(f"[misclass] {out_dir}/misclassified_examples.pdf  n={rows}")


def fig_concept_exemplars(primary: dict, out_dir: Path, data_root: Path,
                            filename_lookup: dict, top_k: int = 3):
    """Per concept, top-K test cells maximizing that concept's predicted probability."""
    pred = primary["pred"]
    con_p = pred["test"]["concept_logits"].sigmoid().numpy()
    test_idx = pred["test_idx"]
    concepts = pred["concepts"]
    classes = pred["class_names"]
    y = pred["test"]["labels"].numpy().astype(int)
    fig, axes = plt.subplots(len(concepts), top_k,
                              figsize=(1.6 * top_k, 1.5 * len(concepts)))
    if top_k == 1:
        axes = axes[:, None]
    for c, name in enumerate(concepts):
        order = np.argsort(con_p[:, c])[::-1][:top_k]
        for j, ci in enumerate(order):
            img = _load_image(test_idx, ci, filename_lookup, data_root)
            ax = axes[c, j]
            if img is not None:
                ax.imshow(img.resize((150, 150)))
            ax.set_xticks([]); ax.set_yticks([])
            true_lab = ",".join(classes[k] for k in np.where(y[ci] == 1)[0])
            ax.set_title(f"p={con_p[ci, c]:.2f}\n{true_lab[:14]}", fontsize=6)
        axes[c, 0].set_ylabel(name.replace("_", " "), fontsize=7, rotation=0, ha="right", va="center")
    fig.suptitle("Top cells per concept (predicted)", fontsize=11)
    fig.tight_layout()
    fig.savefig(out_dir / "concept_exemplars.pdf")
    fig.savefig(out_dir / "concept_exemplars.png", dpi=150)
    plt.close(fig)
    print(f"[exemplars] {out_dir}/concept_exemplars.pdf")


# ----------------------------- Confusion ------------------------------------
def fig_confusion(primary: dict, out_dir: Path):
    """Two-panel figure: (left) raw co-occurrence count matrix with absolute numbers
    so a biologist can see how many cells were misclassified; (right) per-class
    precision/recall/F1 bar so the headline F1 in the table is reproducible.
    """
    pred = primary["pred"]
    cls_p = pred["test"]["class_logits"].sigmoid().numpy()
    y = pred["test"]["labels"].numpy().astype(int)
    classes = pred["class_names"]
    K = y.shape[1]
    e = primary.get("eval", {})
    thr = np.array(e.get("classification_tuned", {}).get("thresholds", [0.5] * K))
    pred_h = (cls_p >= thr[None, :]).astype(int)

    # Co-occurrence count matrix (multi-label: a cell with k true labels and m predicted
    # contributes 1 to k*m cells). On the diagonal: cells where true_k=1 AND pred_k=1.
    cm = np.zeros((K, K), dtype=int)
    for i in range(len(y)):
        true_k = np.where(y[i] == 1)[0]
        pred_k = np.where(pred_h[i] == 1)[0]
        for tk in true_k:
            for pk in pred_k:
                cm[tk, pk] += 1

    # Per-class binary precision/recall/F1 (these are what the headline table reports).
    from sklearn.metrics import precision_score, recall_score, f1_score
    prec = [precision_score(y[:, k], pred_h[:, k], zero_division=0) for k in range(K)]
    rec = [recall_score(y[:, k], pred_h[:, k], zero_division=0) for k in range(K)]
    f1 = [f1_score(y[:, k], pred_h[:, k], zero_division=0) for k in range(K)]
    n_pos = [int(y[:, k].sum()) for k in range(K)]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5),
                              gridspec_kw={"width_ratios": [1.4, 1.0]})

    # Left: count matrix with absolute counts
    ax = axes[0]
    im = ax.imshow(cm, cmap="Blues")
    vmax = cm.max()
    for i in range(K):
        for j in range(K):
            color = "white" if cm[i, j] > vmax * 0.5 else "black"
            ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                    fontsize=10, color=color)
    ax.set_xticks(range(K)); ax.set_yticks(range(K))
    ax.set_xticklabels(classes, fontsize=8, rotation=30, ha="right")
    ax.set_yticklabels(classes, fontsize=8)
    ax.set_xlabel("Predicted class (multi-label, threshold-tuned)")
    ax.set_ylabel("True class")
    ax.set_title("Co-occurrence counts on test set\n(diagonal = correctly classified; off-diagonal = where the model got confused)")
    plt.colorbar(im, ax=ax, fraction=0.046, label="# (cell, true class, pred class) triples")

    # Right: per-class P / R / F1 grouped bars (these are the headline metrics).
    ax = axes[1]
    x = np.arange(K)
    width = 0.27
    ax.bar(x - width, prec, width=width, label="Precision", color="#1f77b4")
    ax.bar(x, rec, width=width, label="Recall", color="#ff7f0e")
    ax.bar(x + width, f1, width=width, label="F1", color="#2ca02c")
    for i, v in enumerate(f1):
        ax.text(x[i] + width, v + 0.01, f"{v:.2f}", ha="center", fontsize=7)
    ax.axhline(0.90, color="r", lw=0.8, ls="--", label="target 0.90")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{c}\n(n={n_pos[i]})" for i, c in enumerate(classes)],
                        fontsize=8, rotation=30, ha="right")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("Score (test, tuned thresholds)")
    ax.legend(loc="lower left", fontsize=8)
    ax.set_title("Per-class precision / recall / F1 (binary one-vs-rest)\nSame F1 numbers as the main results table")

    fig.tight_layout()
    fig.savefig(out_dir / "confusion_matrix.pdf")
    fig.savefig(out_dir / "confusion_matrix.png", dpi=150)
    plt.close(fig)
    print(f"[confusion] {out_dir}/confusion_matrix.pdf")


# ----------------------------- Main ------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out_root", default=str(HERE / "outputs"))
    ap.add_argument("--fig_dir", default=str(HERE / "figures_v2"))
    ap.add_argument("--data_root", default=str(WORKDIR / "data" / "gr_neutro_extended"))
    ap.add_argument("--csv", default=str(WORKDIR / "data" / "gr_neutro_extended" / "annotations.csv"))
    ap.add_argument("--primary_tag", required=True,
                    help="Run/ensemble used for attention + galleries.")
    ap.add_argument("--leaderboard_tags", required=True,
                    help="Comma-separated tags shown in the bar charts and tables.")
    args = ap.parse_args()

    out_root = Path(args.out_root)
    fig_dir = Path(args.fig_dir)
    fig_dir.mkdir(parents=True, exist_ok=True)
    data_root = Path(args.data_root)

    rows_by_idx = {}
    with open(args.csv) as f:
        r = csv.reader(f)
        next(r)
        for i, row in enumerate(r):
            rows_by_idx[i] = row[0]

    primary = load_run(args.primary_tag, out_root)
    leaderboard_tags = [t.strip() for t in args.leaderboard_tags.split(",") if t.strip()]
    runs = {t: load_run(t, out_root) for t in leaderboard_tags}

    fig_main_table(runs, fig_dir)
    fig_per_class_breakdown(runs, fig_dir)
    fig_per_concept_breakdown(runs, fig_dir)
    fig_attention_overlay(primary, fig_dir, data_root, rows_by_idx)
    fig_classified_examples(primary, fig_dir, data_root, rows_by_idx, k_per_class=2)
    fig_misclassified_examples(primary, fig_dir, data_root, rows_by_idx, n=12)
    fig_concept_exemplars(primary, fig_dir, data_root, rows_by_idx, top_k=3)
    fig_confusion(primary, fig_dir)

    # Tarball
    import tarfile
    tar_path = fig_dir.parent / "figures_v2.tar.gz"
    with tarfile.open(tar_path, "w:gz") as tar:
        for p in sorted(fig_dir.iterdir()):
            tar.add(p, arcname=p.name)
    print(f"[tar] {tar_path}")


if __name__ == "__main__":
    main()
